USE [master]
GO
/****** Object:  Database [LCWaikiki]    Script Date: 4.05.2022 00:49:02 ******/
CREATE DATABASE [LCWaikiki]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LCWaikiki', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LCWaikiki.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LCWaikiki_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LCWaikiki_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LCWaikiki] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LCWaikiki].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LCWaikiki] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LCWaikiki] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LCWaikiki] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LCWaikiki] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LCWaikiki] SET ARITHABORT OFF 
GO
ALTER DATABASE [LCWaikiki] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LCWaikiki] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LCWaikiki] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LCWaikiki] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LCWaikiki] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LCWaikiki] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LCWaikiki] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LCWaikiki] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LCWaikiki] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LCWaikiki] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LCWaikiki] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LCWaikiki] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LCWaikiki] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LCWaikiki] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LCWaikiki] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LCWaikiki] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LCWaikiki] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LCWaikiki] SET RECOVERY FULL 
GO
ALTER DATABASE [LCWaikiki] SET  MULTI_USER 
GO
ALTER DATABASE [LCWaikiki] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LCWaikiki] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LCWaikiki] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LCWaikiki] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LCWaikiki] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LCWaikiki] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'LCWaikiki', N'ON'
GO
ALTER DATABASE [LCWaikiki] SET QUERY_STORE = OFF
GO
USE [LCWaikiki]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](32) NOT NULL,
	[LastName] [nvarchar](32) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[IsAdmin] [bit] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Users] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[USER NAMES]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[USER NAMES] AS
SELECT Id, Firstname + ' ' + LastName AS FullName
FROM dbo.Users
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Categories] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
	[Color] [nvarchar](max) NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[ImageUrl] [nvarchar](max) NULL,
	[CategoryId] [int] NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_Products] UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[PRODUCT DETAILS]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[PRODUCT DETAILS] AS
SELECT Products.Name as [Ürün Adı], 
Categories.Name as Kategori,
Products.Color as Renk,
CAST(Products.Price as varchar(50)) + ' TL' as Fiyat
FROM Products 
JOIN Categories
ON PRODUCTS.CategoryId = Categories.Id
GO
/****** Object:  Table [dbo].[ShoppingLists]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ShoppingLists](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IsEditable] [bit] NOT NULL,
	[UserId] [int] NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_ShoppingLists] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_ShoppingLists] UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetails]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[Amount] [int] NOT NULL,
	[ShoppingListId] [int] NOT NULL,
	[IsAddedToCart] [bit] NOT NULL,
 CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[SHOPPING LIST PRODUCT COUNTS]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   VIEW [dbo].[SHOPPING LIST PRODUCT COUNTS] AS
SELECT ShoppingLists.Name, COUNT(ShoppingLists.Name) AS [Product Count]
FROM ShoppingLists
FULL JOIN OrderDetails
ON OrderDetails.ShoppingListId = ShoppingLists.Id
GROUP BY ShoppingLists.Name
GO
/****** Object:  Table [dbo].[Logging]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logging](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Header] [varchar](150) NOT NULL,
	[Description] [varchar](500) NOT NULL,
 CONSTRAINT [PK_Logging] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [NC_ListId_ProductId]    Script Date: 4.05.2022 00:49:02 ******/
CREATE UNIQUE NONCLUSTERED INDEX [NC_ListId_ProductId] ON [dbo].[OrderDetails]
(
	[ProductId] ASC,
	[ShoppingListId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [NC_Mail_Password]    Script Date: 4.05.2022 00:49:02 ******/
CREATE NONCLUSTERED INDEX [NC_Mail_Password] ON [dbo].[Users]
(
	[Email] ASC,
	[Password] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ShoppingLists] ADD  DEFAULT (CONVERT([bit],(1))) FOR [IsEditable]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (CONVERT([bit],(0))) FOR [IsAdmin]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_Products_ProductId] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderDetails_Products_ProductId]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_ShoppingLists_ShoppingListId] FOREIGN KEY([ShoppingListId])
REFERENCES [dbo].[ShoppingLists] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderDetails_ShoppingLists_ShoppingListId]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Categories_CategoryId]
GO
ALTER TABLE [dbo].[ShoppingLists]  WITH CHECK ADD  CONSTRAINT [FK_ShoppingLists_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ShoppingLists] CHECK CONSTRAINT [FK_ShoppingLists_Users_UserId]
GO
/****** Object:  StoredProcedure [dbo].[SP_GET_ACTIVE_SHOPPING_LISTS]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_GET_ACTIVE_SHOPPING_LISTS]
AS
BEGIN
	SELECT Id FROM dbo.ShoppingLists
	WHERE IsEditable = 1
END
GO
/****** Object:  Trigger [dbo].[TRG_INSERT]    Script Date: 4.05.2022 00:49:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER [dbo].[TRG_INSERT]
ON [dbo].[Products]
AFTER INSERT
AS
BEGIN

DECLARE @DATA NVARCHAR(MAX)

SELECT @DATA = Name FROM INSERTED

INSERT INTO Logging(Header, Description)
VALUES('INSERTED',@DATA + ' eklendi')

END
GO
ALTER TABLE [dbo].[Products] ENABLE TRIGGER [TRG_INSERT]
GO
USE [master]
GO
ALTER DATABASE [LCWaikiki] SET  READ_WRITE 
GO
